name: CI

on:
  push:
    branches: [main]
    paths-ignore: ["*.md", "schematics/**"]
  pull_request:
    paths-ignore: ["*.md", "schematics/**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-src rustfmt clippy
          targets: riscv32imc-unknown-none-elf
      - uses: Swatinem/rust-cache@v2
      - name: Setup config
        run: cp .cargo/config.toml.example .cargo/config.toml
      - run: cargo fmt --check
      - run: cargo build --release
      - run: cargo clippy -- -D warnings
